<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `sms.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $SMS__t_PhoneSeq;

if(!isset($SMS__t_PhoneSeq))
{
    $SMS__t_PhoneSeq = IcePHP_defineSequence('::SMS::PhoneSeq', $IcePHP__t_string);
}

global $SMS__t_SmsDict;

if(!isset($SMS__t_SmsDict))
{
    $SMS__t_SmsDict = IcePHP_defineDictionary('::SMS::SmsDict', $IcePHP__t_string, $IcePHP__t_string);
}

global $SMS__t_SmsSend;
global $SMS__t_SmsSendPrx;

if(!interface_exists('SMS_SmsSend'))
{
    interface SMS_SmsSend extends Ice_Object
    {
        public function sendStandard($phones, $tempId);
        public function sendScheduler($phones, $tempId, $date);
        public function sendIdentifyingCode($phone, $tempId);
        public function checkIdentifyingCode($phone, $code);
        public function getSmsTemplates();
        public function test();
    }

    class SMS_SmsSendPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::SMS::SmsSend', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::SMS::SmsSend', $facet);
        }

        public static function ice_staticId()
        {
            return '::SMS::SmsSend';
        }
    }

    $SMS__t_SmsSend = IcePHP_defineClass('::SMS::SmsSend', 'SMS_SmsSend', -1, true, false, $Ice__t_Object, null, null);

    $SMS__t_SmsSendPrx = IcePHP_defineProxy($SMS__t_SmsSend);

    IcePHP_defineOperation($SMS__t_SmsSend, 'sendStandard', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, array($SMS__t_SmsDict, false, 0), null);
    IcePHP_defineOperation($SMS__t_SmsSend, 'sendScheduler', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, array($SMS__t_SmsDict, false, 0), null);
    IcePHP_defineOperation($SMS__t_SmsSend, 'sendIdentifyingCode', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, array($SMS__t_SmsDict, false, 0), null);
    IcePHP_defineOperation($SMS__t_SmsSend, 'checkIdentifyingCode', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, array($SMS__t_SmsDict, false, 0), null);
    IcePHP_defineOperation($SMS__t_SmsSend, 'getSmsTemplates', 0, 0, 0, null, null, array($SMS__t_SmsDict, false, 0), null);
    IcePHP_defineOperation($SMS__t_SmsSend, 'test', 0, 0, 0, null, null, array($SMS__t_SmsDict, false, 0), null);
}
?>
